<a href="https://colab.research.google.com/github/Mithiles-19/OIBSIP/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/AB_NYC_2019.csv")

# Inspect dataset
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [ ]:
# Check missing values
df.isna().sum().sort_values(ascending=False)

last_review                       10052
reviews_per_month                 10052
host_name                            21
name                                 16
neighbourhood_group                   0
neighbourhood                         0
id                                    0
host_id                               0
longitude                             0
latitude                              0
room_type                             0
price                                 0
number_of_reviews                     0
minimum_nights                        0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
df["name"] = df["name"].fillna("Unknown")
df["host_name"] = df["host_name"].fillna("Unknown")


df["reviews_per_month"] = df["reviews_per_month"].fillna(0)

df["last_review"] = pd.to_datetime(df["last_review"], errors="coerce")

df.isna().sum()

id                                    0
name                                  0
host_id                               0
host_name                             0
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]

print(f"Duplicates removed: {before - after}")

Duplicates removed: 0

In [ ]:

text_cols = ["neighbourhood_group", "neighbourhood", "room_type"]

for col in text_cols:
    df[col] = df[col].str.strip().str.title()


df = df[df["price"] > 0]

In [ ]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["price"] < lower) | (df["price"] > upper)]
outliers.shape

(2972, 16)

In [ ]:
df_clean = df[(df["price"] >= lower) & (df["price"] <= upper)]

df.shape, df_clean.shape

((48884, 16), (45912, 16))

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45912 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              45912 non-null  int64
 1   name                            45912 non-null  object
 2   host_id                         45912 non-null  int64
 3   host_name                       45912 non-null  object
 4   neighbourhood_group             45912 non-null  object
 5   neighbourhood                   45912 non-null  object
 6   latitude                        45912 non-null  float64
 7   longitude                       45912 non-null  float64
 8   room_type                       45912 non-null  object
 9   price                           45912 non-null  int64
 10  minimum_nights                  45912 non-null  int64
 11  number_of_reviews               45912 non-null  int64
 12  last_review                     36901 non-null  datetime64[ns]
 13  reviews_per_month               45912 non-null  float64
 14  calculated_host_listings_count  45912 non-null  int64
 15  availability_365                45912 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 6.0+ MB